const mongoose = require("mongoose");
const Station = require("./models/StationModel");

mongoose
  .connect("mongodb://169.47.198.147/ZipItSolar", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log("MONGO CONNECTION OPEN");
  })
  .catch((err) => {
    console.log("Err", err);
    console.log("ERROR");
  });

const seedStations = [
  {
    StationName: "Benton Nissan - Hoover",
    StreetAddress: "1640 Montgomery Hwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35216",
  },
  {
    StationName: "Matt Bowers Nissan Eastern Shore",
    StreetAddress: "29788 Fredrick Blvd",
    City: "Daphne",
    State: "AL",
    ZIP: "36526",
  },
  {
    StationName: "Lynn Layton Nissan",
    StreetAddress: "2402 Highway 31 S",
    City: "Decatur",
    State: "AL",
    ZIP: "35601",
  },
  {
    StationName: "Jack Ingram Motors",
    StreetAddress: "227 Eastern Bypass",
    City: "Montgomery",
    State: "AL",
    ZIP: "36117",
  },
  {
    StationName: "Nissan of Albertville",
    StreetAddress: "9736 US Highway 431",
    City: "Albertville",
    State: "AL",
    ZIP: "35950",
  },
  {
    StationName: "Massey Automotive",
    StreetAddress: "600 W Bypass",
    City: "Andalusia",
    State: "AL",
    ZIP: "36420",
  },
  {
    StationName: "Lynch Nissan - Auburn",
    StreetAddress: "140 W Creek Pkwy",
    City: "Auburn",
    State: "AL",
    ZIP: "36830",
  },
  {
    StationName: "Benton Nissan - Bessemer",
    StreetAddress: "5487 Academy Way",
    City: "Bessemer",
    State: "AL",
    ZIP: "35022",
  },
  {
    StationName: "Jim Burke Nissan",
    StreetAddress: "1300 3rd Ave N",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "Serra Nissan",
    StreetAddress: "1500 Center Pt Pkwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35215",
  },
  {
    StationName: "McKinnon Nissan",
    StreetAddress: "135 Price Dr",
    City: "Clanton",
    State: "AL",
    ZIP: "35046",
  },
  {
    StationName: "Bondy&apos;s Nissan",
    StreetAddress: "3693 W Main St",
    City: "Dothan",
    State: "AL",
    ZIP: "36305",
  },
  {
    StationName: "Mitchell Nissan",
    StreetAddress: "1640 E Park Ave",
    City: "Enterprise",
    State: "AL",
    ZIP: "36330",
  },
  {
    StationName: "University Nissan - Florence",
    StreetAddress: "248 Cox Creek Pkwy",
    City: "Florence",
    State: "AL",
    ZIP: "35630",
  },
  {
    StationName: "Nissan of Gadsden",
    StreetAddress: "1701 Rainbow Dr",
    City: "Gadsden",
    State: "AL",
    ZIP: "35901",
  },
  {
    StationName: "Landers McLarty Nissan",
    StreetAddress: "6520 University Dr NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "Nissan of Mobile",
    StreetAddress: "1015 E Interstate 65 Service Rd S",
    City: "Mobile",
    State: "AL",
    ZIP: "36606",
  },
  {
    StationName: "Benton Nissan",
    StreetAddress: "1834 US Highway 78 E",
    City: "Oxford",
    State: "AL",
    ZIP: "36203",
  },
  {
    StationName: "Townsend Nissan",
    StreetAddress: "2620 Skyland Blvd E",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35405",
  },
  {
    StationName: "Serra Nissan - Sylacauga",
    StreetAddress: "80 James Payton Blvd",
    City: "Sylacauga",
    State: "AL",
    ZIP: "35150",
  },
  {
    StationName: "CAPITAL PARK CAPITAL PARK 72",
    StreetAddress: "6941 Hwy 72 W",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "Bridge Street Town Centre",
    StreetAddress: "325 The Bridge St",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "Holiday Inn Express &amp; Suites",
    StreetAddress: "2407 Beltline Rd SW",
    City: "Decatur",
    State: "AL",
    ZIP: "35601",
  },
  {
    StationName: "Publix #1512",
    StreetAddress: "230 20th St S",
    City: "Birmingham",
    State: "AL",
    ZIP: "35233",
  },
  {
    StationName: "UAB HILL STU CTR",
    StreetAddress: "1500 University Blvd",
    City: "Birmingham",
    State: "AL",
    ZIP: "35233",
  },
  {
    StationName: "UAB COMM HLTH BLDG",
    StreetAddress: "933 19th St S",
    City: "Birmingham",
    State: "AL",
    ZIP: "35205",
  },
  {
    StationName: "UAB EXPRESS LOT 4 1",
    StreetAddress: "316 10th St S",
    City: "Birmingham",
    State: "AL",
    ZIP: "35233",
  },
  {
    StationName: "Damn Yankees Restaurant",
    StreetAddress: "2190 Almon St",
    City: "Heflin",
    State: "AL",
    ZIP: "36264",
  },
  {
    StationName: "THE AVE STATION AVENUE EV1",
    StreetAddress: "201 Jefferson st",
    City: "Huntsville",
    State: "AL",
    ZIP: "35801",
  },
  {
    StationName: "Tony Serra Nissan",
    StreetAddress: "1724 Cherokee Ave SW",
    City: "Cullman",
    State: "AL",
    ZIP: "35055",
  },
  {
    StationName: "Phenix City Parks and Recreation",
    StreetAddress: "1500 Airport Rd",
    City: "Phenix City",
    State: "AL",
    ZIP: "36867",
  },
  {
    StationName: "FAIRFIELD INN - Tesla Supercharger",
    StreetAddress: "21282 Athens-Limestone Blvd.",
    City: "Athens",
    State: "AL",
    ZIP: "35613",
  },
  {
    StationName: "Auburn Mall - Tesla Supercharger",
    StreetAddress: "1627 Opelika Road",
    City: "Auburn",
    State: "AL",
    ZIP: "36830",
  },
  {
    StationName: "Uptown Entertainment District - Tesla Supercharger",
    StreetAddress: "2221 Richard Arrington Junior Blvd.",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "Hampton Inn Greenville - Tesla Supercharger",
    StreetAddress: "219 Interstate Drive",
    City: "Greenville",
    State: "AL",
    ZIP: "36037",
  },
  {
    StationName: "The Bel Air Mall - Tesla Supercharger",
    StreetAddress: "3201 Airport Blvd",
    City: "Mobile",
    State: "AL",
    ZIP: "36606",
  },
  {
    StationName: "Oxford Exchange - Tesla Supercharger",
    StreetAddress: "1105 Oxford Exchange Blvd",
    City: "Oxford",
    State: "AL",
    ZIP: "36203",
  },
  {
    StationName: "Love&apos;s Travel Stop - Tesla Supercharger",
    StreetAddress: "905 Steele Station Road",
    City: "Steele",
    State: "AL",
    ZIP: "35987",
  },
  {
    StationName: "WHOLE FOODS MKT HUNTSVILLE 2",
    StreetAddress: "2501 Memorial Pkwy SW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35801",
  },
  {
    StationName: "Tru by Hilton Auburn - Tesla Destination",
    StreetAddress: "2411 W Pace Blvd",
    City: "Auburn",
    State: "AL",
    ZIP: "36830",
  },
  {
    StationName: "Grand Bohemian Hotel Mountain Brook - Tesla Destination",
    StreetAddress: "2655 Lane Park Rd",
    City: "Birmingham",
    State: "AL",
    ZIP: "35223",
  },
  {
    StationName: "Embassy Suites Birmingham - Hoover - Tesla Destination",
    StreetAddress: "2960 John Hawkins Pkwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35244",
  },
  {
    StationName:
      "Hampton Inn Birmingham I-65/Lakeshore Drive - Tesla Destination",
    StreetAddress: "30 State Farm Pkwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35209",
  },
  {
    StationName: "Home2 Suites Birmingham Colonnade - Tesla Destination",
    StreetAddress: "3920 Colonnade Pkwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35243",
  },
  {
    StationName:
      "Fairfield Inn &amp; Suites Birmingham Colonnade - Tesla Destination",
    StreetAddress: "3930 Colonnade Pkwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35243",
  },
  {
    StationName: "SpringHill Suites Birmingham Colonnade - Tesla Destination",
    StreetAddress: "3950 Colonnade Pkwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35243",
  },
  {
    StationName: "Hilton Birmingham Perimeter Park - Tesla Destination",
    StreetAddress: "8 Perimeter Park S",
    City: "Birmingham",
    State: "AL",
    ZIP: "35243",
  },
  {
    StationName: "Jay Landings Marina - Tesla Destination",
    StreetAddress: "1600 Hwy 20",
    City: "Decatur",
    State: "AL",
    ZIP: "35601",
  },
  {
    StationName: "TownePlace Suites by Marriott Dothan - Tesla Destination",
    StreetAddress: "201 Retail Dr",
    City: "Dothan",
    State: "AL",
    ZIP: "36303",
  },
  {
    StationName: "Benson&apos;s Appliance Center - Tesla Destination",
    StreetAddress: "501 N McKenzie St",
    City: "Foley",
    State: "AL",
    ZIP: "36535",
  },
  {
    StationName:
      "Fairfield Inn &amp; Suites by Marriott Gadsden - Tesla Destination",
    StreetAddress: "116 Walker St",
    City: "Gadsden",
    State: "AL",
    ZIP: "35904",
  },
  {
    StationName: "LuLu&apos;s Gulf Shores - Tesla Destination",
    StreetAddress: "200 E 25th Ave",
    City: "Gulf Shores",
    State: "AL",
    ZIP: "36542",
  },
  {
    StationName:
      "Hampton Inn Huntsville/Village of Providence - Tesla Destination",
    StreetAddress: "328 Providence Main St",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "The Kate Shepard House Bed and Breakfast - Tesla Destination",
    StreetAddress: "1552 Monterey Pl",
    City: "Mobile",
    State: "AL",
    ZIP: "36604",
  },
  {
    StationName:
      "Hilton Garden Inn Mobile West I-65/Airport Blvd. - Tesla Destination",
    StreetAddress: "828 W I-65 Service Rd S",
    City: "Mobile",
    State: "AL",
    ZIP: "36609",
  },
  {
    StationName: "Sleep Inn Eastchase - Tesla Destination",
    StreetAddress: "10150 Chantilly Pkwy",
    City: "Montgomery",
    State: "AL",
    ZIP: "36117",
  },
  {
    StationName: "Best Western Montgomery I-85 North Hotel - Tesla Destination",
    StreetAddress: "5225 Carmichael Rd",
    City: "Montgomery",
    State: "AL",
    ZIP: "36106",
  },
  {
    StationName:
      "Fairfield Inn &amp; Suites Montgomery-EastChase Parkway - Tesla Destination",
    StreetAddress: "8970 Eastchase Pkwy",
    City: "Montgomery",
    State: "AL",
    ZIP: "36117",
  },
  {
    StationName: "Hilton Garden Inn Orange Beach - Tesla Destination",
    StreetAddress: "23092 Perdido Beach Blvd",
    City: "Orange Beach",
    State: "AL",
    ZIP: "36561",
  },
  {
    StationName: "Holiday Inn Express Orange Beach - Tesla Destination",
    StreetAddress: "24700 Perdido Beach Blvd",
    City: "Orange Beach",
    State: "AL",
    ZIP: "36561",
  },
  {
    StationName: "Hampton Inn &amp; Suites Orange Beach - Tesla Destination",
    StreetAddress: "25518 Perdido Beach Blvd",
    City: "Orange Beach",
    State: "AL",
    ZIP: "36561",
  },
  {
    StationName: "The Gulf - Tesla Destination",
    StreetAddress: "27500 Perdido Beach Blvd",
    City: "Orange Beach",
    State: "AL",
    ZIP: "36561",
  },
  {
    StationName:
      "Holiday Inn Express &amp; Suites Prattville South - Tesla Destination",
    StreetAddress: "203 Legends Ct",
    City: "Prattville",
    State: "AL",
    ZIP: "36066",
  },
  {
    StationName: "Home2 Suites by Hilton Prattville - Tesla Destination",
    StreetAddress: "2505 Legends Dr",
    City: "Prattville",
    State: "AL",
    ZIP: "36066",
  },
  {
    StationName: "Hotel Indigo Tuscaloosa Downtown - Tesla Destination",
    StreetAddress: "111 Greensboro Ave",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35401",
  },
  {
    StationName: "TAMERON HONDA SHOP 01",
    StreetAddress: "9871 Justina Ave",
    City: "Daphne",
    State: "AL",
    ZIP: "36526",
  },
  {
    StationName: "Hilton Garden Inn Birmingham/Trussville - Tesla Destination",
    StreetAddress: "3230 Edwards Lake Pkwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35235",
  },
  {
    StationName:
      "University of North Alabama - Parking Lot E - Tesla Destination",
    StreetAddress: "1 Harrison Plaza",
    City: "Florence",
    State: "AL",
    ZIP: "35632",
  },
  {
    StationName:
      "University of North Alabama - Parking Lot A - Tesla Destination",
    StreetAddress: "1 Harrison Plaza",
    City: "Florence",
    State: "AL",
    ZIP: "35632",
  },
  {
    StationName: "Haint Blue Brewing Company - Tesla Destination",
    StreetAddress: "806 Monroe St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "Hilton Garden Inn Montgomery - EastChase - Tesla Destination",
    StreetAddress: "7665 EastChase Pkwy",
    City: "Mongtomery",
    State: "AL",
    ZIP: "36117",
  },
  {
    StationName:
      "Grand Hotel Marriott Resort Golf Club &amp; Spa - Tesla Destination",
    StreetAddress: "One Grand Blvd",
    City: "Point Clear",
    State: "AL",
    ZIP: "36564",
  },
  {
    StationName: "MOBILE BUICK BLDG EV1",
    StreetAddress: "450 St Louis St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "MOBILE STAPLES PAKE EV",
    StreetAddress: "75A St Michael St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "MOBILE FEDERAL BLDG EV",
    StreetAddress: "106 St Joseph St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "MOBILE CATHEDRAL SQ 1",
    StreetAddress: "18 S Jackson St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "MOBILE CRUISE TERMINAL",
    StreetAddress: "Cruise Terminal",
    City: "Mobile",
    State: "AL",
    ZIP: "36603",
  },
  {
    StationName: "MOBILE ST LOUIS ST EV1",
    StreetAddress: "2 St Louis St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "MOBILE CONVENT CTR 2",
    StreetAddress: "Water NB at Dauphin St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "MOBILE MARDIGRAS PARK1",
    StreetAddress: "109 Government St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "MOBILE CONVENT CTR 1",
    StreetAddress: "1 S Water St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "MOBILE BIENVILLE SQ EV",
    StreetAddress: "162 St Francis St",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "USA CHARGING USA 1",
    StreetAddress: "150 Student Services Dr",
    City: "Mobile",
    State: "AL",
    ZIP: "36608",
  },
  {
    StationName: "USA CHARGING USA 2",
    StreetAddress: "5851 USA Dr N",
    City: "Mobile",
    State: "AL",
    ZIP: "36608",
  },
  {
    StationName: "REDSTONE HD DCFAST HOG",
    StreetAddress: "15100 AL-20",
    City: "Madison",
    State: "AL",
    ZIP: "35756",
  },
  {
    StationName: "Jasper Sleep Inn &amp; Suites",
    StreetAddress: "90 Carl Cannon Boulevard",
    City: "Jasper",
    State: "AL",
    ZIP: "35501",
  },
  {
    StationName: "CEC4BYRDS 4BYRDS",
    StreetAddress: "9450 S Main St",
    City: "Brantley",
    State: "AL",
    ZIP: "36009",
  },
  {
    StationName: "MOBILE OLD GAYFERS EV1",
    StreetAddress: "160 Conti St.",
    City: "Mobile",
    State: "AL",
    ZIP: "36602",
  },
  {
    StationName: "Walmart 356 (Auburn, AL)",
    StreetAddress: "1717 S College St",
    City: "Auburn",
    State: "AL",
    ZIP: "36832",
  },
  {
    StationName: "CULLMANELECTRIC CEC MAIN OFFICE",
    StreetAddress: "1749 Eva Rd NE",
    City: "Cullman",
    State: "AL",
    ZIP: "35055",
  },
  {
    StationName: "THE BEACH CLUB SPECTRUM RESORT",
    StreetAddress: "453 Beach Club Trail",
    City: "Gulf Shores",
    State: "AL",
    ZIP: "36542",
  },
  {
    StationName: "Phenix City Riverwalk",
    StreetAddress: "1350 Whitewater Ave",
    City: "Phenix City",
    State: "AL",
    ZIP: "36867",
  },
  {
    StationName: "Phenix City Municipal Court",
    StreetAddress: "1111 Broad St",
    City: "Phenix City",
    State: "AL",
    ZIP: "36867",
  },
  {
    StationName: "Auburn University - Stadium Parking Deck - Non-networked",
    StreetAddress: "425 Heisman Dr",
    City: "Auburn",
    State: "AL",
    ZIP: "36849",
  },
  {
    StationName: "Auburn University - South Donahue Parking Deck",
    StreetAddress: "501 Biggio Dr",
    City: "Auburn",
    State: "AL",
    ZIP: "36832",
  },
  {
    StationName: "Auburn University - RO Parking",
    StreetAddress: "901 W Thach Ave",
    City: "Auburn",
    State: "AL",
    ZIP: "36832",
  },
  {
    StationName: "Auburn University - South Quad Parking Deck",
    StreetAddress: "330 Lem Morrison Dr",
    City: "Auburn",
    State: "AL",
    ZIP: "36849",
  },
  {
    StationName:
      "Renaissance Montgomery Hotel &amp; Spa at the Convention Center",
    StreetAddress: "201 Tallapoosa St",
    City: "Montgomery",
    State: "AL",
    ZIP: "36104",
  },
  {
    StationName: "Downtown Montgomery",
    StreetAddress: "209 Commerce St",
    City: "Montgomery",
    State: "AL",
    ZIP: "36104",
  },
  {
    StationName:
      "Montgomery Marriott Prattville Hotel &amp; Conference Center at Capitol Hill",
    StreetAddress: "2500 Legends Cir",
    City: "Prattville",
    State: "AL",
    ZIP: "36066",
  },
  {
    StationName: "Hampton Inn &amp; Suites Prattville",
    StreetAddress: "2590 Cobbs Ford Rd",
    City: "Prattville",
    State: "AL",
    ZIP: "36066",
  },
  {
    StationName: "Hampton Inn &amp; Suites Prattville - Tesla",
    StreetAddress: "2590 Cobbs Ford Rd",
    City: "Prattville",
    State: "AL",
    ZIP: "36066",
  },
  {
    StationName: "The Grand Hotel Golf Resort &amp; Spa",
    StreetAddress: "One Grand Blvd",
    City: "Point Clear",
    State: "AL",
    ZIP: "36564",
  },
  {
    StationName: "HARTSELLE 1 HARTSELLE 1",
    StreetAddress: "110 Hickory St SW",
    City: "Hartselle",
    State: "AL",
    ZIP: "35640",
  },
  {
    StationName: "Walmart 1462 (Greenville, AL)",
    StreetAddress: "501 Willow Ln",
    City: "Greenville",
    State: "AL",
    ZIP: "36037",
  },
  {
    StationName: "Walmart 809 (Oxford, AL)",
    StreetAddress: "92 Plaza Ln",
    City: "Oxford",
    State: "AL",
    ZIP: "36203",
  },
  {
    StationName: "RIVIERA EV RIVIERA SOLAR1",
    StreetAddress: "714 N McKenzie St",
    City: "Foley",
    State: "AL",
    ZIP: "36535",
  },
  {
    StationName: "RIVIERA EV RIVIERA FOLEY",
    StreetAddress: "700 N McKenzie St",
    City: "Foley",
    State: "AL",
    ZIP: "36535",
  },
  {
    StationName: "FD STATION 1",
    StreetAddress: "201 Brown St",
    City: "Boaz",
    State: "AL",
    ZIP: "35957",
  },
  {
    StationName: "SRS EV STATION 1",
    StreetAddress: "200 Town Madison Blvd",
    City: "Madison",
    State: "AL",
    ZIP: "35758",
  },
  {
    StationName: "Walmart 661 (Athens, AL)",
    StreetAddress: "1011 US Hwy 72 E",
    City: "Athens",
    State: "AL",
    ZIP: "35611",
  },
  {
    StationName: "FB ALABAMA NHA1 STATION 3",
    StreetAddress: "100 S. Profile Pl. NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35810",
  },
  {
    StationName: "7SPC NASA USSRC R",
    StreetAddress: "1 Tranquility Base",
    City: "Huntsville",
    State: "AL",
    ZIP: "35805",
  },
  {
    StationName: "Walmart 1212 (Saraland, AL)",
    StreetAddress: "1095 Industrial Pkwy",
    City: "Saraland",
    State: "AL",
    ZIP: "36571",
  },
  {
    StationName: "TownePlace Suites Montgomery EastChase - Tesla Destination",
    StreetAddress: "2845 EastChase Lane",
    City: "Montgomery",
    State: "AL",
    ZIP: "36117",
  },
  {
    StationName: "Walmart 423 (Alabaster, AL)",
    StreetAddress: "630 COLONIAL PKWY",
    City: "Alabaster",
    State: "AL",
    ZIP: "35007",
  },
  {
    StationName: "Sam&apos;s Club 8106 (Montgomery, AL)",
    StreetAddress: "1080 EASTERN BLVD",
    City: "Montgomery",
    State: "AL",
    ZIP: "36117",
  },
  {
    StationName: "UAB EXPRESS LOT 4 2",
    StreetAddress: "316 10th St S",
    City: "Birmingham",
    State: "AL",
    ZIP: "35233",
  },
  {
    StationName: "WHOLE FOODS MKT HUNTSVILLE 1",
    StreetAddress: "2501 Memorial Pkwy SW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35801",
  },
  {
    StationName: "TAMERON HONDA SHOP 02",
    StreetAddress: "9871 Justina Ave",
    City: "Daphne",
    State: "AL",
    ZIP: "36526",
  },
  {
    StationName: "FB ALABAMA NHA1 STATION 1",
    StreetAddress: "100 S. Profile Pl. NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35810",
  },
  {
    StationName: "FB ALABAMA NHA1 STATION 2",
    StreetAddress: "100 S. Profile Pl. NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35810",
  },
  {
    StationName: "Hampton Inn Birmingham/Trussville",
    StreetAddress: "1940 Edwards Lake Rd",
    City: "Trussville",
    State: "AL",
    ZIP: "35235",
  },
  {
    StationName: "Birmingham-Shuttlesworth International Airport",
    StreetAddress: "5900 Messer-Airport Hwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35212",
  },
  {
    StationName: "DU ELECTRIC STATION 2",
    StreetAddress: "207 N Saint Andrews St",
    City: "Dothan",
    State: "AL",
    ZIP: "36303",
  },
  {
    StationName: "DU ELECTRIC STATION 1",
    StreetAddress: "207 North Saint Andrews St",
    City: "Dothan",
    State: "AL",
    ZIP: "36303",
  },
  {
    StationName: "BSC",
    StreetAddress: "900 Arkadelphia Rd",
    City: "Birmingham",
    State: "AL",
    ZIP: "35254",
  },
  {
    StationName: "SCOTTSBORO EPB MAIN OFFICE",
    StreetAddress: "404 East Willow Street",
    City: "Scottsboro",
    State: "AL",
    ZIP: "35768",
  },
  {
    StationName: "CENTURY AUTO VOLVO FRONT 2PT",
    StreetAddress: "3800 University Dr NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35816",
  },
  {
    StationName: "RIVIERA EV MANCIS 2",
    StreetAddress: "706 Belrose Ave",
    City: "Daphne",
    State: "AL",
    ZIP: "36526",
  },
  {
    StationName: "RIVIERA EV MANCIS 1",
    StreetAddress: "706 Belrose Ave",
    City: "Daphne",
    State: "AL",
    ZIP: "36526",
  },
  {
    StationName: "RIVIERA EV CITY HALL",
    StreetAddress: "1705 Main St",
    City: "Daphne",
    State: "AL",
    ZIP: "36526",
  },
  {
    StationName: "MBHUNTSVILLE MB HUNTSVILLE",
    StreetAddress: "6520 University Dr NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "BOAZ AL BOAZ REC CENTER",
    StreetAddress: "200 Elizabeth St",
    City: "Boaz",
    State: "AL",
    ZIP: "35957",
  },
  {
    StationName: "MBBHM DELIVERY",
    StreetAddress: "4539 Grants Mill Trail",
    City: "Birmingham",
    State: "AL",
    ZIP: "35210",
  },
  {
    StationName: "MBBHM SERVICE BAY",
    StreetAddress: "4517 Grants Mill Trail",
    City: "Birmingham",
    State: "AL",
    ZIP: "35210",
  },
  {
    StationName: "ALEXANDER CITY STATION 1",
    StreetAddress: "James D. Nabors Dr",
    City: "Alexander City",
    State: "AL",
    ZIP: "35010",
  },
  {
    StationName: "APC STATION 6 AC",
    StreetAddress: "630 17th St N",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "APC STATION 4 AC",
    StreetAddress: "630 17th St N",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "ALEXANDER CITY STATION 2",
    StreetAddress: "James D. Nabors Dr",
    City: "Alexander City",
    State: "AL",
    ZIP: "35010",
  },
  {
    StationName: "ALEXANDER CITY STATION 3",
    StreetAddress: "James D. Nabors Dr",
    City: "Alexander City",
    State: "AL",
    ZIP: "35010",
  },
  {
    StationName: "JACK INGRAM CUSTOMER 1",
    StreetAddress: "217 Eastern Blvd",
    City: "Montgomery",
    State: "AL",
    ZIP: "36117",
  },
  {
    StationName: "APC STATION 1 AC",
    StreetAddress: "630 17th St N",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "APC STATION 5 AC",
    StreetAddress: "630 17th St N",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "CRMC CRMC-1 - L2LEFT",
    StreetAddress: "POB2 Parking Lot - Station 1",
    City: "Cullman",
    State: "AL",
    ZIP: "35058",
  },
  {
    StationName: "CRMC CRMC-2- L2RIGHT",
    StreetAddress: "POB2 Parking Lot - Station 2",
    City: "Cullman",
    State: "AL",
    ZIP: "35058",
  },
  {
    StationName: "Target - Tesla Supercharger",
    StreetAddress: "2567 Berryhill Road",
    City: "Montgomery",
    State: "AL",
    ZIP: "36117",
  },
  {
    StationName: "Lane Parke Shopping Mall - Tesla Supercharger",
    StreetAddress: "1000 Jemison Lane",
    City: "Mountain Brook",
    State: "AL",
    ZIP: "35223",
  },
  {
    StationName: "HIGHLAND STATION 4",
    StreetAddress: "151 Du Rhu Drive",
    City: "Mobile",
    State: "AL",
    ZIP: "36608",
  },
  {
    StationName: "CATRANIS_ENTERP BOULA BOULA EV1",
    StreetAddress: "1859 Airport Blvd",
    City: "Mobile",
    State: "AL",
    ZIP: "36606",
  },
  {
    StationName: "CUSTOMER STATIO MBOM-1",
    StreetAddress: "3060 Dauphin St",
    City: "Mobile",
    State: "AL",
    ZIP: "36606",
  },
  {
    StationName: "FPIA RIGHT STATION",
    StreetAddress: "501 Gault Ave N",
    City: "Fort Payne",
    State: "AL",
    ZIP: "35967",
  },
  {
    StationName: "FPIA LEFT STATION",
    StreetAddress: "501 Gault Ave N",
    City: "Fort Payne",
    State: "AL",
    ZIP: "35967",
  },
  {
    StationName: "HENRY HOUSE BUILDING 5",
    StreetAddress: "1435 Balch Rd",
    City: "Madison",
    State: "AL",
    ZIP: "35757",
  },
  {
    StationName: "Bramlett Buick GMC",
    StreetAddress: "3305 US-31",
    City: "Decatur",
    State: "AL",
    ZIP: "35603",
  },
  {
    StationName: "RIVIERA EV RIVIERAOFFICEDC",
    StreetAddress: "413 E Laurel Ave",
    City: "Foley",
    State: "AL",
    ZIP: "36535",
  },
  {
    StationName: "TUSCALOOSA CITY NRW - WEST",
    StreetAddress: "201 Rice Mine Rd Loop",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35406",
  },
  {
    StationName: "TUSCALOOSA CITY NRW - EAST",
    StreetAddress: "201 Rice Mine Rd Loop",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35406",
  },
  {
    StationName: "JULIO JONES KIA STATION 1",
    StreetAddress: "4301 Greensboro Ave",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35405",
  },
  {
    StationName: "HQ CHARGER 1 HQ CHARGER 1",
    StreetAddress: "29627 Renaissance Blvd",
    City: "Daphne",
    State: "AL",
    ZIP: "36526",
  },
  {
    StationName:
      "Holiday Inn Express &amp; Suites Tuscaloosa - Tesla Supercharger",
    StreetAddress: "6350 Interstate Drive",
    City: "Cottondale",
    State: "AL",
    ZIP: "35453",
  },
  {
    StationName: "Greystone Pointe Auburn",
    StreetAddress: "1600 E Samford Ave",
    City: "Auburn",
    State: "AL",
    ZIP: "36830",
  },
  {
    StationName: "EBOFG GUNTERSVILLE PD",
    StreetAddress: "329 Gunter Ave",
    City: "Guntersville",
    State: "AL",
    ZIP: "35976",
  },
  {
    StationName: "UAB 17TH ST #1",
    StreetAddress: "900 17th St S",
    City: "Birmingham",
    State: "AL",
    ZIP: "35205",
  },
  {
    StationName: "Buc-ee&apos;s - Tesla Supercharger",
    StreetAddress: "6910 Buc-ee&apos;s Blvd",
    City: "Leeds",
    State: "AL",
    ZIP: "35094",
  },
  {
    StationName: "HIGHLAND STATION 3",
    StreetAddress: "151 Du Rhu Drive",
    City: "Mobile",
    State: "AL",
    ZIP: "36608",
  },
  {
    StationName: "EAGLE PIKE ROAD EAGLE",
    StreetAddress: "12645 US-80",
    City: "Pike Road",
    State: "AL",
    ZIP: "36064",
  },
  {
    StationName: "RIVIERA EV SF CITY HALL",
    StreetAddress: "7361 Spanish Fort Blvd",
    City: "Spanish Fort",
    State: "AL",
    ZIP: "36527",
  },
  {
    StationName: "FORT RUCKER BUILDING 5700",
    StreetAddress: "5700 Novosel St",
    City: "Fort Rucker",
    State: "AL",
    ZIP: "36362",
  },
  {
    StationName: "CLIFT FARM CLIFT FARM",
    StreetAddress: "165 John Thomas Dr",
    City: "Madison",
    State: "AL",
    ZIP: "35757",
  },
  {
    StationName: "ROYAL AUTO VOLVO SALES",
    StreetAddress: "3016 Columbiana Rd",
    City: "Vestavia Hills",
    State: "AL",
    ZIP: "35216",
  },
  {
    StationName: "OPELIKA POWER S RAIL ROAD #1",
    StreetAddress: "601 S Railroad Ave",
    City: "Opelika",
    State: "AL",
    ZIP: "36801",
  },
  {
    StationName: "OPELIKA POWER S RAIL ROAD #2",
    StreetAddress: "601 S Railroad Ave",
    City: "Opelika",
    State: "AL",
    ZIP: "36801",
  },
  {
    StationName: "OPELIKA POWER RTJ MARRIOTT #1",
    StreetAddress: "3700 Robert Trent Jones Trail",
    City: "Opelika",
    State: "AL",
    ZIP: "36801",
  },
  {
    StationName: "OPELIKA POWER RTJ MARRIOTT #2",
    StreetAddress: "3700 Robert Trent Jones Trail",
    City: "Opelika",
    State: "AL",
    ZIP: "36801",
  },
  {
    StationName: "OPELIKA POWER OPELIKA DEPOT#1",
    StreetAddress: "1016 S Railroad Ave",
    City: "Opelika",
    State: "AL",
    ZIP: "36801",
  },
  {
    StationName: "OPELIKA POWER OPELIKA DEPOT#2",
    StreetAddress: "1032 S Railroad Ave",
    City: "Opelika",
    State: "AL",
    ZIP: "36801",
  },
  {
    StationName: "OPELIKA POWER COURT HOUSE #1",
    StreetAddress: "205 S 9th St",
    City: "Opelika",
    State: "AL",
    ZIP: "36801",
  },
  {
    StationName: "OPELIKA POWER COURT HOUSE #2",
    StreetAddress: "205 S 9th St",
    City: "Opelika",
    State: "AL",
    ZIP: "36801",
  },
  {
    StationName: "FAIRHOPE STATION 2",
    StreetAddress: "23 N Section Street",
    City: "Fairhope",
    State: "AL",
    ZIP: "36532",
  },
  {
    StationName: "FAIRHOPE CITY HALL #1",
    StreetAddress: "160 US-98 ALT",
    City: "Fairhope",
    State: "AL",
    ZIP: "36532",
  },
  {
    StationName: "FAIRHOPE CITY HALL #2",
    StreetAddress: "160 US-98 ALT",
    City: "Fairhope",
    State: "AL",
    ZIP: "36532",
  },
  {
    StationName: "FAIRHOPE CITY HALL #3",
    StreetAddress: "160 US-98 ALT",
    City: "Fairhope",
    State: "AL",
    ZIP: "36532",
  },
  {
    StationName: "Buc-ee&apos;s - Tesla Supercharger",
    StreetAddress: "20403 Co Road 68",
    City: "Robertsdale",
    State: "AL",
    ZIP: "36567",
  },
  {
    StationName: "Tiger Crossing Shopping Center - Tesla Supercharger",
    StreetAddress: "1617 South College Street",
    City: "Auburn",
    State: "AL",
    ZIP: "36832",
  },
  {
    StationName: "Brompton Valero Travel Center",
    StreetAddress: "2700 Kelly Creek Rd",
    City: "Moody",
    State: "AL",
    ZIP: "35004",
  },
  {
    StationName: "DOWNTOWN OZARK LEFT STATION",
    StreetAddress: "217 S Union Ave",
    City: "Ozark",
    State: "AL",
    ZIP: "36360",
  },
  {
    StationName: "DOWNTOWN OZARK RIGHT STATION",
    StreetAddress: "217 S Union Ave",
    City: "Ozark",
    State: "AL",
    ZIP: "36360",
  },
  {
    StationName: "COURT SQUARE COURT SQUARE",
    StreetAddress: "1-K Court Square",
    City: "Andalusia",
    State: "AL",
    ZIP: "36420",
  },
  {
    StationName: "CAT CARD GRAND RIVERS 1",
    StreetAddress: "6200 Grand River Blvd E",
    City: "Leeds",
    State: "AL",
    ZIP: "35094",
  },
  {
    StationName: "CAT CARD GRAND RIVERS 2",
    StreetAddress: "6200 Grand River Blvd E",
    City: "Leeds",
    State: "AL",
    ZIP: "35094",
  },
  {
    StationName: "CAT CARD GRAND RIVERS 4",
    StreetAddress: "6200 Grand River Blvd E",
    City: "Leeds",
    State: "AL",
    ZIP: "35094",
  },
  {
    StationName: "Red Roof Inn &amp; Suites",
    StreetAddress: "1218 Kelli Dr",
    City: "Athens",
    State: "AL",
    ZIP: "35613",
  },
  {
    StationName: "CAT CARD GRAND RIVERS 3",
    StreetAddress: "6200 Grand River Blvd E",
    City: "Leeds",
    State: "AL",
    ZIP: "35094",
  },
  {
    StationName: "MidCity District - Tesla Supercharger",
    StreetAddress: "5909 University Dr",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "MAPLES BOLIGEE DC 2",
    StreetAddress: "17619 Co Rd 20",
    City: "Boligee",
    State: "AL",
    ZIP: "35443",
  },
  {
    StationName: "MAPLES BOLIGEE DC 1",
    StreetAddress: "17619 Co Rd 20",
    City: "Boligee",
    State: "AL",
    ZIP: "35443",
  },
  {
    StationName: "ALBERTA MIDSTATES DC 2",
    StreetAddress: "2301 University Blvd E",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35404",
  },
  {
    StationName: "Li-Cycle",
    StreetAddress: "1601 Boone Blvd",
    City: "Northport",
    State: "AL",
    ZIP: "35476",
  },
  {
    StationName: "ALBERTA MIDSTATES DC 1",
    StreetAddress: "2319 University Blvd E",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35404",
  },
  {
    StationName: "SPARKFUND CITY WALK 3",
    StreetAddress: "1842 9th Ave N",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "SPARKFUND CITY WALK 4",
    StreetAddress: "900 19th St N",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "SPARKFUND CITY WALK 1",
    StreetAddress: "2300 Reverend Abraham Woods Jr Boulevard",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "SPARKFUND CITY WALK 2",
    StreetAddress: "2300 Reverend Abraham Woods Jr Boulevard",
    City: "Birmingham",
    State: "AL",
    ZIP: "35203",
  },
  {
    StationName: "The Collins",
    StreetAddress: "1100 Enterprise Way North West",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "Southern Co R&amp;D Energy Research Facility",
    StreetAddress: "922 Old Grants Mill Rd",
    City: "Irondale",
    State: "AL",
    ZIP: "35210",
  },
  {
    StationName: "Twickenham",
    StreetAddress: "200 Davis Circle Southwest",
    City: "Huntsville",
    State: "AL",
    ZIP: "35801",
  },
  {
    StationName: "MBHUNTSVILLE DC FAST CHARGER",
    StreetAddress: "6520 University Dr",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "RIVIERA EV COFFEE SHOP",
    StreetAddress: "218 N Alston St",
    City: "Foley",
    State: "AL",
    ZIP: "36535",
  },
  {
    StationName: "ENCORE ENCORE 1",
    StreetAddress: "1643 Montgomery Hwy",
    City: "Vestavia Hills",
    State: "AL",
    ZIP: "35216",
  },
  {
    StationName: "ENCORE ENCORE 2",
    StreetAddress: "1643 Montgomery Hwy",
    City: "Vestavia Hills",
    State: "AL",
    ZIP: "35216",
  },
  {
    StationName: "FB ALABAMA NHA3 STATION 2",
    StreetAddress: "100 S. Profile Pl. NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35810",
  },
  {
    StationName: "FB ALABAMA NHA3 STATION 3",
    StreetAddress: "100 S. Profile Pl. NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35810",
  },
  {
    StationName: "Auburn University - College of Veterinary Medicine",
    StreetAddress: "1130 Wire Rd",
    City: "Auburn",
    State: "AL",
    ZIP: "36832",
  },
  {
    StationName: "Holiday Inn Express &amp; Suites",
    StreetAddress: "2407 Beltline Rd SW",
    City: "Decatur",
    State: "AL",
    ZIP: "35601",
  },
  {
    StationName: "TUSCALOOSA CITY COT-RDP-1",
    StreetAddress: "180 Greensboro Ave",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35401",
  },
  {
    StationName: "TUSCALOOSA CITY COT - RDP2",
    StreetAddress: "180 Greensboro Ave",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35401",
  },
  {
    StationName: "Mercedes-Benz Visitor Center (Vance, AL)",
    StreetAddress: "11 Mercedes Dr",
    City: "Vance",
    State: "AL",
    ZIP: "35490",
  },
  {
    StationName: "Phoenix VIII",
    StreetAddress: "27008 Perdido Beach Blvd",
    City: "Orange Beach",
    State: "AL",
    ZIP: "36561",
  },
  {
    StationName: "BMWOFTUSCALOOSA 1",
    StreetAddress: "3537 Skyland E Blvd",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35405",
  },
  {
    StationName: "BMWOFTUSCALOOSA 2",
    StreetAddress: "3537 Skyland E Blvd",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35405",
  },
  {
    StationName: "CFD Research HQ",
    StreetAddress: "6820 Moquin Drive Northwest",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "COPT - Secured Gateway",
    StreetAddress: "Redstone Gateway Southwest",
    City: "Huntsville",
    State: "AL",
    ZIP: "35808",
  },
  {
    StationName: "COPT - Market St",
    StreetAddress: "4000 Market Street Southwest",
    City: "Huntsville",
    State: "AL",
    ZIP: "35808",
  },
  {
    StationName: "ALLEN FOOD 11 ALLEN FOODMART1",
    StreetAddress: "2197 Eastern Valley Rd",
    City: "Bessemer",
    State: "AL",
    ZIP: "35022",
  },
  {
    StationName: "ALLEN FOOD 11 ALLEN FOODMART2",
    StreetAddress: "2197 Eastern Valley Rd",
    City: "Bessemer",
    State: "AL",
    ZIP: "35022",
  },
  {
    StationName: "ALLEN FOOD 11 ALLEN FOODMART3",
    StreetAddress: "2197 Eastern Valley Rd",
    City: "Bessemer",
    State: "AL",
    ZIP: "35022",
  },
  {
    StationName: "ALLEN FOOD 11 ALLEN FOODMART4",
    StreetAddress: "2197 Eastern Valley Rd",
    City: "Bessemer",
    State: "AL",
    ZIP: "35022",
  },
  {
    StationName: "CITYOFGENEVA GENEVAEV1",
    StreetAddress: "614 S Commerce St",
    City: "Geneva",
    State: "AL",
    ZIP: "36340",
  },
  {
    StationName: "MERCEDES-FAST MERC-FAST1",
    StreetAddress: "2309 Ross Clark Cir",
    City: "Dothan",
    State: "AL",
    ZIP: "36301",
  },
  {
    StationName: "FB ALABAMA NHA3 STATION 1",
    StreetAddress: "100 S. Profile Pl. NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35810",
  },
  {
    StationName: "MERCEDES-FAST MERCEDES CT4000",
    StreetAddress: "2309 Ross Clark Cir",
    City: "Dothan",
    State: "AL",
    ZIP: "36301",
  },
  {
    StationName: "BILL PENNEY SER BILL PENNEY CPF",
    StreetAddress: "4808 University Dr NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35816",
  },
  {
    StationName: "Piggly Wiggly Grocery - Tesla Supercharger",
    StreetAddress: "90 Liberty Hill Pl",
    City: "Evergreen",
    State: "AL",
    ZIP: "36401",
  },
  {
    StationName: "Winn-Dixie - Tesla Supercharger",
    StreetAddress: "1151 Ross Clark Cir",
    City: "Dothan",
    State: "AL",
    ZIP: "36301",
  },
  {
    StationName: "TUSC HYUNDAI LEVEL 3 #1",
    StreetAddress: "3831 Hargrove Rd E",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35405",
  },
  {
    StationName: "Ashley Garage",
    StreetAddress: "3207 Governors Dr SW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35805",
  },
  {
    StationName: "7SPC NASA USSRC L",
    StreetAddress: "1 Tranquility Base",
    City: "Huntsville",
    State: "AL",
    ZIP: "35805",
  },
  {
    StationName: "Buc-ees #43 (Leeds, AL)",
    StreetAddress: "6900 Buc-ee&apos;s Blvd",
    City: "Leeds",
    State: "AL",
    ZIP: "35094",
  },
  {
    StationName: "ELEMENT WESTIN ELEMENT EV1",
    StreetAddress: "6800 Governors West NW",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "THE WATTS WATTS1",
    StreetAddress: "7235 US-431",
    City: "Owens Cross Roads",
    State: "AL",
    ZIP: "35763",
  },
  {
    StationName: "TANGMART OXFORD TANG MART 1",
    StreetAddress: "600 Quintard Drive",
    City: "Oxford",
    State: "AL",
    ZIP: "36203",
  },
  {
    StationName: "TANGMART OXFORD TANG MART 2",
    StreetAddress: "600 Quintard Drive",
    City: "Oxford",
    State: "AL",
    ZIP: "36203",
  },
  {
    StationName: "Piedmont",
    StreetAddress: "109 N Center Ave",
    City: "Piedmont",
    State: "AL",
    ZIP: "36272",
  },
  {
    StationName: "Crenshaw Guest House - Tesla Destination",
    StreetAddress: "371 N. College Street",
    City: "Auburn",
    State: "AL",
    ZIP: "36830",
  },
  {
    StationName:
      "La Quinta Inn &amp; Suites by Wyndham Oxford - Anniston - Tesla Destination",
    StreetAddress: "100 Colonial Drive",
    City: "Oxford",
    State: "AL",
    ZIP: "36203",
  },
  {
    StationName: "TRU by Hilton Prattville - Tesla Destination",
    StreetAddress: "2633 Legends Parkway",
    City: "Prattville",
    State: "AL",
    ZIP: "36066",
  },
  {
    StationName:
      "Red Roof Inn &amp; Suites Athens I-65 Exit 351 - Tesla Destination",
    StreetAddress: "1218 Kelli Drive",
    City: "Athens",
    State: "AL",
    ZIP: "35613",
  },
  {
    StationName: "Econo Lodge Oxford - Tesla Destination",
    StreetAddress: "25 ELM STREET",
    City: "OXFORD",
    State: "AL",
    ZIP: "36203",
  },
  {
    StationName: "Best Western Brewton Inn &amp; Suites - Tesla Destination",
    StreetAddress: "1115 Douglas Ave",
    City: "Brewton",
    State: "AL",
    ZIP: "36426",
  },
  {
    StationName: "SERRA HYUNDAI HYUNDAICPE250 1",
    StreetAddress: "1503 Gadsden Hwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35235",
  },
  {
    StationName: "SERRA HYUNDAI HYUNDAICPE250 2",
    StreetAddress: "1503 Gadsden Hwy",
    City: "Birmingham",
    State: "AL",
    ZIP: "35235",
  },
  {
    StationName: "JULIO JONES KIA KIA SALES",
    StreetAddress: "4301 Greensboro Ave",
    City: "Tuscaloosa",
    State: "AL",
    ZIP: "35405",
  },
  {
    StationName: "LEXUS EV STAND LEX HSV 1",
    StreetAddress: "6580 University Dr",
    City: "Huntsville",
    State: "AL",
    ZIP: "35806",
  },
  {
    StationName: "CITY OF EUFAULA SCC 1",
    StreetAddress: "101-113 N Orange Ave",
    City: "Eufaula",
    State: "AL",
    ZIP: "36027",
  },
];

const SeedDb = async () => {
  await Station.insertMany(seedStations);
};

SeedDb().then(() => {
  mongoose.connection.close();
});
